# Generated by Django 3.2.7 on 2021-10-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
