# Generated by Django 3.2.3 on 2021-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/user_avatar/default.png', upload_to='images/user_avatar'),
        ),
    ]
