# Generated by Django 3.2.3 on 2021-11-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0006_auto_20211026_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img.pmg', upload_to='images/user_avatar'),
        ),
    ]
