# Generated by Django 3.2.3 on 2021-11-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
