# Generated by Django 3.2.3 on 2021-11-04 14:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Points', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name=django.contrib.auth.models.User)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
