# Generated by Django 3.2.9 on 2021-11-04 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_check',
            name='receipt_id',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
