# Generated by Django 3.2.9 on 2021-11-04 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0003_alter_pay_check_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_check',
            name='pay_time',
            field=models.DateTimeField(default=1, verbose_name='payment time'),
            preserve_default=False,
        ),
    ]
