# Generated by Django 3.2.9 on 2021-11-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0004_pay_check_pay_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_check',
            name='receipt_id',
        ),
    ]
