# Generated by Django 3.2.9 on 2021-11-05 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0005_remove_pay_check_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_check',
            name='receipt_id',
            field=models.IntegerField(default=1, max_length=99999),
            preserve_default=False,
        ),
    ]
