# Generated by Django 3.2.9 on 2021-11-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0006_pay_check_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_check',
            name='receipt_id',
            field=models.IntegerField(),
        ),
    ]
