# Generated by Django 3.2.9 on 2021-11-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay_system', '0007_alter_pay_check_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_check',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
