# Generated by Django 3.2.9 on 2021-11-06 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0008_pay_check_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_check',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 22, 8, 56, 627590, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
