# Generated by Django 3.2.9 on 2021-11-06 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0009_alter_pay_check_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_check',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 22, 13, 38, 330033, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
