# Generated by Django 3.2.9 on 2021-11-06 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0010_alter_pay_check_pay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_check',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay_check',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pay_check',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 22, 39, 14, 31608, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
