# Generated by Django 3.2.9 on 2021-11-07 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0011_auto_20211107_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_check',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='pay_check',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 0, 4, 30, 125034, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
