# Generated by Django 3.2.9 on 2021-11-07 00:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0013_alter_pay_check_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_check',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 0, 20, 25, 991464, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
