# Generated by Django 3.2.7 on 2021-11-12 22:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 17, 42, 927993, tzinfo=utc), verbose_name='payment time')),
                ('plan_cost', models.DecimalField(decimal_places=2, default=99, max_digits=5)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 17, 42, 927993, tzinfo=utc), verbose_name='payment time')),
                ('plan_cost', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 17, 42, 927027, tzinfo=utc), verbose_name='payment time')),
                ('plan_cost', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
