# Generated by Django 3.2.7 on 2021-11-12 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 18, 10, 72774, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='proplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 18, 10, 73736, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='vipplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 18, 10, 73736, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
