# Generated by Django 3.2.7 on 2021-11-13 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0002_auto_20211113_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 20, 34, 8, 595790, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='proplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 20, 34, 8, 606117, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='vipplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 20, 34, 8, 607154, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
