# Generated by Django 3.2.7 on 2021-12-04 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0018_auto_20211126_1717'),
    ]

    operations = [

    ]
