# Generated by Django 3.2.9 on 2021-11-26 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0020_auto_20211126_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceplan',
            name='plan_cost',
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 23, 5, 8, 541121, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
