# Generated by Django 3.2.9 on 2021-11-26 23:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PricingPlans', '0025_auto_20211127_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 23, 48, 38, 239196, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.CharField(max_length=15),
        ),
    ]
