# Generated by Django 3.2.9 on 2021-11-27 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0026_auto_20211127_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 17, 59, 7, 313578, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.DecimalField(choices=[(9, 'Base Plan'), (25, 'Pro Plan'), (49, 'Vip Plan')], decimal_places=2, max_digits=50),
        ),
    ]
