# Generated by Django 3.2.9 on 2021-11-29 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0027_auto_20211127_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 19, 57, 58, 987868, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
