# Generated by Django 3.2.7 on 2021-12-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0018_auto_20211205_0004'),
        ('PricingPlans', '0027_auto_20211127_1959'),
    ]

    operations = [
    ]
