# Generated by Django 3.2.9 on 2021-11-29 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0028_alter_priceplan_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 10, 21, 704012, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
