# Generated by Django 3.2.7 on 2021-12-02 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0030_alter_priceplan_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 5, 47, 749679, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
