# Generated by Django 3.2.7 on 2021-12-02 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0031_alter_priceplan_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 21, 41, 8, 549592, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.CharField(choices=[('BasePlan', 'Base Plan'), ('ProPlan', 'Pro Plan'), ('VipPlan', 'Vip Plan')], max_length=25),
        ),
    ]
