# Generated by Django 3.2.7 on 2021-12-04 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0035_auto_20211204_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 0, 30, 43, 693511, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.CharField(choices=[('BasePlan', 'Base Plan'), ('ProPlan', 'Pro Plan'), ('VipPlan', 'Vip Plan')], max_length=100),
        ),
    ]
