# Generated by Django 3.2.7 on 2021-12-04 00:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0036_auto_20211204_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 0, 31, 8, 777393, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
