# Generated by Django 3.2.7 on 2021-12-04 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0040_auto_20211204_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 2, 51, 43, 630480, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
