# Generated by Django 3.2.7 on 2021-12-08 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0048_alter_priceplan_payment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlanTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 0, 55, 13, 1019, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
