# Generated by Django 3.2.7 on 2021-12-11 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0049_auto_20211208_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 1, 19, 55, 936829, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
