# Generated by Django 3.2.7 on 2021-12-11 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0050_alter_priceplan_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 1, 20, 56, 122927, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
