# Generated by Django 3.2.7 on 2021-12-11 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0054_alter_priceplan_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 20, 45, 4, 560784, tzinfo=utc), verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.CharField(choices=[(9, 'Base Plan'), (25, 'Pro Plan'), (49, 'Vip Plan')], max_length=100),
        ),
    ]
