# Generated by Django 3.2.7 on 2021-12-15 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0056_auto_20211215_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 2, 37, 0, 967608, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
