# Generated by Django 3.2.7 on 2021-12-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0028_merge_0018_auto_20211205_0004_0027_auto_20211127_1959'),
        ('PricingPlans', '0057_alter_priceplan_payment_time'),
    ]

    operations = [
    ]
