# Generated by Django 3.2.7 on 2021-12-19 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PricingPlans', '0058_merge_20211219_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 14, 29, 25, 71722, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
