# Generated by Django 3.2.7 on 2021-11-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='time',
        ),
        migrations.AddField(
            model_name='route',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
