# Generated by Django 3.2.7 on 2021-11-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0003_alter_route_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_point_x',
            new_name='end_point_lat',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='end_point_y',
            new_name='end_point_long',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='distance',
            new_name='journey_dist',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='rating',
            new_name='journey_rating',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='date_time',
            new_name='journey_time',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='name_route',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_point_x',
            new_name='start_point_lat',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_point_y',
            new_name='start_point_long',
        ),
    ]
