# Generated by Django 3.2.7 on 2021-10-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Messenger.groupchat', verbose_name='group_chat'),
            preserve_default=False,
        ),
    ]
