# Generated by Django 3.2.7 on 2021-10-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.ImageField(upload_to='image/user_avatar'),
        ),
        migrations.CreateModel(
            name='GroupChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='body')),
                ('description', models.TextField(max_length=2000, verbose_name='body')),
                ('image', models.ImageField(upload_to='image/group_avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_avatar',
            },
        ),
    ]
