# Generated by Django 3.2.7 on 2021-10-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_auto_20211015_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchats',
            options={'verbose_name': 'group_chats'},
        ),
    ]
