# Generated by Django 3.2.7 on 2021-10-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_message_group_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messenger.groupchat', verbose_name='Group Chat'),
        ),
    ]
