# Generated by Django 3.2.7 on 2021-10-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20211009_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ('-timestamp',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
