# Generated by Django 3.2.7 on 2021-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_alter_groupchats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchats',
            name='image',
            field=models.ImageField(default='images/group_avatar/default.png', upload_to='images/group_avatar'),
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
