# Generated by Django 3.2 on 2021-10-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0005_auto_20211024_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'verbose_name': 'Group chat'},
        ),
        migrations.AddField(
            model_name='message',
            name='group_chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Messenger.groupchat', verbose_name='Group Chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.TextField(max_length=200, verbose_name='name'),
        ),
    ]
