# Generated by Django 3.2.7 on 2021-11-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0006_auto_20211031_1700'),
        ('Messenger', '0010_auto_20211107_2246'),
    ]

    operations = [
    ]
