# Generated by Django 3.2.7 on 2021-11-11 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0011_merge_0006_auto_20211031_1700_0010_auto_20211107_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=2000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
