# Generated by Django 3.2.7 on 2021-12-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0012_auto_20211121_1708'),
        ('Messenger', '0013_auto_20211129_2158'),
    ]

    operations = [
    ]
