# Generated by Django 3.2.7 on 2021-12-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0012_auto_20211111_0330'),
        ('Messenger', '0013_alter_groupchat_image'),
    ]

    operations = [
    ]
