# Generated by Django 3.2.7 on 2021-12-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0014_merge_0012_auto_20211121_1708_0013_auto_20211129_2158'),
        ('Messenger', '0014_merge_20211219_1612'),
    ]

    operations = [
    ]
