# Generated by Django 2.2.10 on 2021-12-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0014_merge_0012_auto_20211121_1708_0013_auto_20211129_2158'),
        ('Messenger', '0013_alter_groupchat_image'),
    ]

    operations = [
    ]
