# Generated by Django 3.2.7 on 2021-12-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0015_merge_20211219_1621'),
        ('Messenger', '0015_merge_20211219_1747'),
    ]

    operations = [
    ]
