# Generated by Django 3.2.7 on 2021-11-11 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0003_auto_20211031_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
