# Generated by Django 3.2.8 on 2021-10-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'order in progress'), (2, 'order delivered'), (3, 'order canceled')], default=1)),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('delivered_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
