# Generated by Django 2.2.10 on 2021-10-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211024_1001'),
        ('orders', '0002_auto_20211017_1729'),
    ]

    operations = [
    ]
