# Generated by Django 3.2.7 on 2021-11-10 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntf_type', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms')], default='email', max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=999)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntf_from', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntf_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
