# Generated by Django 3.2.7 on 2021-11-11 01:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.IntegerField()),
                ('pay_time', models.DateTimeField(default=datetime.datetime(2021, 11, 11, 1, 27, 59, 328682, tzinfo=utc), verbose_name='payment time')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
