# Generated by Django 3.2.7 on 2021-11-11 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 23, 14, 27, 938804, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
