# Generated by Django 3.2.7 on 2021-11-12 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0004_alter_paycheck_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 22, 17, 42, 944978, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
