# Generated by Django 3.2.7 on 2021-11-17 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0012_alter_paycheck_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 16, 39, 47, 889523, tzinfo=utc), verbose_name='payment time'),
        ),
    ]
