# Generated by Django 3.2.7 on 2021-11-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PaymentSystem', '0017_alter_paycheck_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='pay_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
